const DESKTOP_VIEWPORT_WIDTH: number = 1600
const DESKTOP_VIEWPORT_HEIGHT: number = 800
const MOBILE_VIEWPORT_WIDTH: number = 800
const MOBILE_VIEWPORT_HEIGHT: number = 800

export {
    DESKTOP_VIEWPORT_HEIGHT,
    DESKTOP_VIEWPORT_WIDTH,
    MOBILE_VIEWPORT_HEIGHT,
    MOBILE_VIEWPORT_WIDTH,
}
