// tslint:disable no-magic-numbers

import { Ms, to } from '../nominal'

const DESKTOP_VIEWPORT_WIDTH: number = 1600
const DESKTOP_VIEWPORT_HEIGHT: number = 800
const MOBILE_VIEWPORT_WIDTH: number = 800
const MOBILE_VIEWPORT_HEIGHT: number = 800

const ANYTHING_ELSE_SELECTOR: string = 'div'

const GOOD_AMOUNT_OF_TIME_TO_SEE_WHAT_THE_SITUATION_IS_WHEN_HEADFULLY_DEBUGGING_TESTS: Ms = to.Ms(3000)

const VERY_HIGH_PRECISION: number = 15
const VERY_LOW_PRECISION: number = 1

export {
    DESKTOP_VIEWPORT_HEIGHT,
    DESKTOP_VIEWPORT_WIDTH,
    MOBILE_VIEWPORT_HEIGHT,
    MOBILE_VIEWPORT_WIDTH,
    ANYTHING_ELSE_SELECTOR,
    GOOD_AMOUNT_OF_TIME_TO_SEE_WHAT_THE_SITUATION_IS_WHEN_HEADFULLY_DEBUGGING_TESTS,
    VERY_HIGH_PRECISION,
    VERY_LOW_PRECISION,
}
