// tslint:disable no-magic-numbers

const ARBITRARILY_LARGE_NUMBER: number = 999999999999

const SQUARE_ROOT_OF_TWO: number = Math.sqrt(2)
const SQUARE_ROOT_OF_THREE: number = Math.sqrt(3)
const CUBE_ROOT_OF_TWO: number = Math.cbrt(2)
const CUBE_ROOT_OF_THREE: number = Math.cbrt(3)

const VALUE_BELOW_WHICH_ROUNDING_IMPLEMENTATION_BREAKS: number = 1 / 1000000

export {
    ARBITRARILY_LARGE_NUMBER,
    SQUARE_ROOT_OF_TWO,
    SQUARE_ROOT_OF_THREE,
    CUBE_ROOT_OF_TWO,
    CUBE_ROOT_OF_THREE,
    VALUE_BELOW_WHICH_ROUNDING_IMPLEMENTATION_BREAKS,
}
