// tslint:disable no-reaching-imports max-file-line-count

export {
    repeat,
    repeatCall,
    deepEqual,
    camelCaseToConstantCase,
    constantCaseToUpperCase,
    camelCaseToLowerCase,
    deepCloneObject,
    deepClone,
    isUndefined,
    allElementsEqual,
    lastElement,
    indexOfLastElement,
    slice,
    INITIAL,
    Maybe,
    keyExistsOnObject,
} from './code/indexForTest'
export {
    distanceBetween,
    rotate,
    X_AXIS,
    Y_AXIS,
    Coordinate,
    computeGreatestCommonDivisor,
    computeLeastCommonMultiple,
    powerSet,
    termialRoot,
    trapezoidalNumber,
    triangularNumber,
    triangularRoot,
    quarterSquareNumber,
    PI,
    negative,
    ONE_HALF,
    THREE_HALVES,
    FOUR_THIRDS,
    TWO_THIRDS,
    FIVE_HALVES,
    round,
    sum,
    product,
    factorial,
    combinationCount,
    evaluate,
    computeLowestTerms,
    computeCommonTerms,
    getNumerator,
    getDenominator,
    multiplyFractions,
    EIGHTH,
    FOURTH,
    THIRD,
    computeLowestCommonDenominator,
} from './math/indexForTest'
export {
    centsTranslationToPitchScalar,
    windowIterationHarmonicStepCount,
    OCTAVE,
    TRITAVE,
    octaveReduce,
    windowReduce,
    SCIENTIFIC_PITCHES,
    ScientificPitchNoteName,
    ScientificPitchOctaveNumber,
    computeEqualDivisionScalars,
    computeOctaveRepeatingScalars,
} from './music/indexForTest'
export {
    apply,
    to,
    from,
    Scalar,
    Cycle,
    Cents,
    Ms,
    Hz,
    Semitones,
    Rotation,
    Base,
    Modulus,
    Ordinal,
    Power,
    Radians,
    Translation,
    Cardinal,
    Numerator,
    Denominator,
    Integer,
    Meters,
    Fraction,
    Space,
    Time,
    Frequency,
    Amplitude,
} from './nominal/indexForTest'
export {
    testArraysAreClose,
    testIsCloseTo,
    testArraysHaveSameElements,
} from './testing/indexForTest'
