// tslint:disable no-reaching-imports

export {
    repeat,
    repeatCall,
    deepEqual,
    camelCaseToConstantCase,
    constantCaseToUpperCase,
    camelCaseToLowerCase,
    deepCloneObject,
    deepClone,
    isDefined,
    allElementsEqual,
    lastElement,
    indexOfLastElement,
    slice,
    INITIAL,
} from './code/indexForTest'
export {
    distanceBetween,
    rotate,
    X_AXIS,
    Y_AXIS,
    Coordinate,
    greatestCommonDivisor,
    lowestCommonMultiple,
    powerSet,
    termialRoot,
    trapezoidalNumber,
    triangularNumber,
    triangularRoot,
    quarterSquareNumber,
    PI,
    negative,
    ONE_HALF,
    THREE_HALVES,
    FOUR_THIRDS,
    TWO_THIRDS,
    FIVE_HALVES,
    round,
    sum,
    product,
    lowestTerms,
    factorial,
    combinationCount,
} from './math/indexForTest'
export {
    centsToPitch,
    windowIterationHarmonicStepCount,
    OCTAVE,
    TRITAVE,
    octaveReduce,
    windowReduce,
    SCIENTIFIC_PITCHES,
    ScientificPitchNoteName,
    ScientificPitchOctaveNumber,
    buildEqualDivisionScalars,
} from './music/indexForTest'
export {
    apply,
    to,
    from,
    Scalar,
    Cycle,
    Cents,
    Ms,
    Hz,
    Semitones,
    Rotation,
    Base,
    Modulus,
    Ordinal,
    Power,
    Radians,
    Translation,
    Cardinal,
    Numerator,
    Denominator,
    Integer,
    Meters,
    Fraction,
    Space,
    Time,
    Frequency,
    Amplitude,
} from './nominal/indexForTest'
export {
    testArraysAreClose,
    testIsCloseTo,
    testArraysHaveSameElements,
} from './testing/indexForTest'
